#!/usr/bin/env bash
# One-time GitHub project bootstrap: labels, milestones, and Milestone 1 issues.
# Requires: GitHub CLI (https://cli.github.com) authenticated via `gh auth login`.
# Safe to re-run: label/milestone creation failures on existing items are ignored;
# issues are skipped if an open issue with the same title exists.
set -euo pipefail

REPO="${1:-SixGricks/FrameFound}"
say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

command -v gh >/dev/null 2>&1 || { echo "GitHub CLI (gh) is required." >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "Run: gh auth login" >&2; exit 1; }

say "Labels"
label() { gh label create "$1" --repo "$REPO" --color "$2" --description "$3" --force >/dev/null; }
label bug             d73a4a "Something is broken"
label feature         a2eeef "New functionality"
label security        b60205 "Security-relevant"
label performance     fbca04 "Speed or resource use"
label frontend        1d76db "Web UI"
label backend         0e8a16 "API, workers, scanner"
label ai              8250df "Transcription, vision, embeddings"
label transcription   8250df "Speech-to-text"
label video           c5def5 "Video processing and playback"
label storage         c5def5 "Filesystems, NAS, derived data"
label adobe           ff7b72 "Premiere Pro integration"
label documentation   0075ca "Docs"
label "good first issue" 7057ff "Small, well-scoped, mentored"
label "help wanted"   008672 "Community contributions welcome"
label "breaking change" e11d21 "Requires migration or major bump"

say "Milestones"
ms() { gh api "repos/$REPO/milestones" -f title="$1" -f description="$2" >/dev/null 2>&1 || true; }
ms "M1: Foundation"        "Compose boots end-to-end; migrations; auth; CI green (v0.1)"
ms "M2: Library indexing"  "Scan, identity, watcher, reconciliation, metadata (v0.2)"
ms "M3: Proxies & previews" "Thumbnails, poster frames, video proxies, signed URLs (v0.3)"
ms "M4: Transcription"     "faster-whisper, timestamped segments, transcript search (v0.4)"
ms "M5: Visual search"     "Embeddings, scene sampling, semantic + hybrid search (v0.5)"
ms "M6: Web UI alpha"      "Polished search, asset detail, dashboards (v0.6)"
ms "M7: Remote access"     "Wizard, Caddy HTTPS, Cloudflare DDNS/Tunnel, 2FA (v0.7)"
ms "M8: Beta hardening"    "Benchmarks, backup/restore, update flow, security review (v0.9)"
ms "M9: Adobe PoC"         "UXP/CEP research, search panel, import via path mapping"

say "Milestone 1 issues"
issue() {  # title, labels, body
  if gh issue list --repo "$REPO" --state open --search "in:title \"$1\"" --json title -q '.[].title' | grep -qxF "$1"; then
    echo "  exists: $1"
  else
    gh issue create --repo "$REPO" --title "$1" --label "$2" --milestone "M1: Foundation" --body "$3" >/dev/null
    echo "  created: $1"
  fi
}

issue "Compose stack boots end-to-end with health checks" backend \
"All services in docker-compose.yml start and report healthy: caddy, web, api, worker, worker-ai, scanner, scheduler, postgres, redis.
- [ ] api /healthz and /readyz check DB + Redis connectivity
- [ ] worker/scheduler start with a real celery app (framefound/worker.py)
- [ ] pip extras [db,queue] wired into apps/server/Dockerfile
- [ ] documented in CONTRIBUTING (clone -> running stack < 30 min)"

issue "Alembic baseline migration and DB session layer" backend \
"SQLAlchemy 2 async engine + session dependency; Alembic init with a baseline migration for the M1 tables (users, sessions, settings, audit_log).
Schema reference: docs/data-model.md. Startup must fail clearly on schema-version mismatch (brief §15.4)."

issue "Local authentication: argon2id, sessions, roles, rate limiting" backend,security \
"Login/logout with argon2id hashing, server-side opaque sessions (Secure/HttpOnly/SameSite cookies), roles admin/user/readonly as a FastAPI authz dependency, login rate limiting with escalating delays, audit-log entries.
Threat model refs: docs/threat-model.md §Spoofing. No default credentials."

issue "First-run setup: expiring setup token creates first admin" backend,security \
"FRAMEFOUND_SETUP_TOKEN (generated by install.sh) is required to create the first admin account and is consumed on first use. Web wizard shell: create admin -> name server -> timezone."

issue "Structured logging and error-response envelope" backend \
"structlog JSON logs across api/worker/scanner; no secrets in logs (brief §23). Consistent problem+json style error envelope for the API."

issue "System health endpoint and page" backend,frontend \
"GET /api/v1/system/health: DB, Redis, data-volume free space, version. Minimal web page rendering it (System Health nav item). Full dashboard lands in M6."

issue "CI: Trivy image scan, license scan, GHCR publish on tags" security,documentation \
"Extend .github/workflows/ci.yml: build web image; Trivy scan with fail threshold; pip-licenses + license-checker report; syft SBOM; publish server+web images to ghcr.io/sixgricks on version tags with a coordinated release manifest (brief §15.2)."

issue "Commit package-lock.json and switch CI/Docker to npm ci" frontend \
"apps/web currently tolerates a missing lockfile (npm install fallback in Dockerfile and ci.yml). Generate and commit package-lock.json, then remove both fallbacks."

issue "Decide: Redis BSD pin vs Valkey" backend,documentation \
"Redis 7.4+ relicensed (RSALv2/SSPL). Pin redis:7.2-alpine or move to valkey. Update docker-compose.yml + docs/licensing.md. ADR if we switch."

issue "Implement file-stability policy (is_file_stable)" backend,storage,"good first issue" \
"apps/server/framefound/scanner/stability.py has the documented decision point for when a mid-copy file is safe to process. Implement + unit tests covering: growing file, zero-byte placeholder, unreadable SMB lock, mtime quiet period. Needed before M2 scanning."

say "Done. Review at: https://github.com/$REPO/issues"
